# Generated by Django 5.0 on 2024-08-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programacion", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seleccion",
            old_name="nivel",
            new_name="nivel_local",
        ),
        migrations.AddField(
            model_name="seleccion",
            name="nivel_visitante",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="horario",
            name="horario",
            field=models.TimeField(),
        ),
    ]
