# Generated by Django 5.0 on 2024-08-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programacion", "0002_rename_nivel_seleccion_nivel_local_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("possicion", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Jugadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=30)),
                ("valor", models.IntegerField()),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pais",
                        to="programacion.seleccion",
                    ),
                ),
                (
                    "posicion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position",
                        to="programacion.posicion",
                    ),
                ),
            ],
        ),
    ]
