# Generated by Django 5.0 on 2024-08-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programacion", "0003_posicion_jugadores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partidos",
            name="horario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hour",
                to="programacion.horario",
            ),
        ),
    ]
